//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonRDVR
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN
    {
        public int A_ID { get; set; }
        public string A_NOM { get; set; }
        public string A_PRENOM { get; set; }
        public string A_EMAIL { get; set; }
        public Nullable<decimal> A_TEL { get; set; }
        public string A_PASSWORD { get; set; }
    }
}
