//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonRDVR
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUREAU_DES_REUNIONS
    {
        public int B_ID { get; set; }
        public long B_NUMERO { get; set; }
        public string B_NOM { get; set; }
        public string B_CHEF { get; set; }
    }
}
