//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonRDVR
{
    using System;
    using System.Collections.Generic;
    
    public partial class FONCTIONNAIRE
    {
        public int U_ID { get; set; }
        public string U_NOM { get; set; }
        public string U_PRENOM { get; set; }
        public Nullable<decimal> U_TEL { get; set; }
        public string U_VILLE { get; set; }
        public string U_EMAIL { get; set; }
        public string U_PASSWORD { get; set; }
        public string U_POSTE { get; set; }
    }
}
