//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonRDVR
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_MonRDV : DbContext
    {
        public DB_MonRDV()
            : base("name=DB_MonRDV")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN> ADMINs { get; set; }
        public virtual DbSet<BUREAU_DES_REUNIONS> BUREAU_DES_REUNIONS { get; set; }
        public virtual DbSet<FONCTIONNAIRE> FONCTIONNAIREs { get; set; }
        public virtual DbSet<REUNION> REUNIONs { get; set; }
        public virtual DbSet<RNADEZ_VOUS> RNADEZ_VOUS { get; set; }
    }
}
