//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonRDVR
{
    using System;
    using System.Collections.Generic;
    
    public partial class RNADEZ_VOUS
    {
        public int RD_ID { get; set; }
        public int U_ID { get; set; }
        public string RD_NOM_PR { get; set; }
        public string RD_PERNOM_PR { get; set; }
        public System.DateTime RD_DATE { get; set; }
        public System.DateTime RD_HEURE { get; set; }
        public string RD_CAUSE { get; set; }
        public Nullable<decimal> RD_TEL_PR { get; set; }
    }
}
